name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        
  deploy_testnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy contracts
        uses: grossiwm/foundry-deploy-action@main
        with:
          rpc-url: ${{ secrets.TESTNET_RPC_URL }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          deploy-script: script/Counter.s.sol:CounterScript
          chain-id: ${{ secrets.TESTNET_CHAIN_ID }}
